### PR TITLE
Update mdn-data

### PR DESCRIPTION
**Pull request by pamelalozano16**

### CODE REVIEW

**Comment by lahmatiy** [comment]
Please remove the `^` from the `mdn/data` version. `mdn/data` can occasionally introduce breaking changes, so we need to pin it to a specific version to ensure stability.

Additionally, run the `npm run review:syntax-patch` command to verify if any patches are no longer necessary.

**Comment by ryo-manba** [comment]
Removing the related patch should resolve this issue.
https://github.com/csstree/csstree/issues/299

**Comment by viceice** [comment]
Can this please be merged and released? 🤗

**Comment by lahmatiy** [comment]
My apologies – I mistakenly chose the wrong option, which caused all commits to be squashed into a single merge commit. Sorry about that.

**Comment by lahmatiy** [comment]
My bad, false alert, everything fine :)

**Pull request merged**
