### PR TITLE
add back support for browserify and webpack

### PR DESCRIPTION
**Pull request by philschatz**
Thanks for a great repository! 

I'm using it at [philschatz/css-plus](https://github.com/philschatz/css-plus) to implement some features in https://www.w3.org/TR/css-content-3/ and https://www.w3.org/TR/css-gcpm-3/ but noticed there is a file missing when building for the browser.

I'm not sure but it seems this could fix it.

### CODE REVIEW

**Comment by lahmatiy** [comment]
Thanks!

Could you explain what is the problem? How do you use it?
I'm not sure `default-syntax.json` is needed now, since it includes into `csstree.js`.

**Comment by philschatz** [comment]
Ah, I forgot to include a console error:

```
$ browserify src/index.js
Error: module not found: "../../data" from file (...)/css-plus/node_modules/css-tree/lib/syntax/default.js
```

I think this is because of [the "browser" section in package.json](https://github.com/csstree/csstree/blob/master/package.json#L25-L27).

I updated the Pull Request to reflect that 😄

**Comment by lahmatiy** [comment]
Thank you for details.
Do you want to build csstree by yourself? In this case use `npm run build`.
Or you require it from `lib` and try to browserify another script?

**Comment by lahmatiy** [comment]
We need `browser` section in `package.json`, since all content of `mdn-data-*.json` files will be included in csstree build. But those files contain too much information that we don't want to have in dist file.

**Comment by philschatz** [comment]
I am using `css-tree` in [css-plus](https://github.com/philschatz/css-plus) (running in NodeJS and a Browser) to parse a file with CSS syntax but I do not need any of the items listed in https://csstree.github.io/docs/syntax.html so I am not sure if that helps answer your question.

An example "CSS" that I would like to parse:

```css
.chapter::after(1)::before(1) { content: "Homework Problems"; }
.chapter::after(1) { 
  class-add: "homework-problems";
  content: move-here('.exercise'); 
}
```

[css-plus](https://github.com/philschatz/css-plus) then uses that to manipulate an HTML file instead of using [XSLT](https://www.w3.org/TR/xslt) (because it is easier to write CSS than XSLT). The example above creates a new element at the end of a `.chapter` with a title, and moves all the `.exercise` elements into it.

Removing the `"browser"` section in `package.json` worked for me (see [Example JSFiddle](https://jsfiddle.net/philschatz/hjk2z4af/) ) but if there is a way to only include the parser that would be wonderful since it would reduce the resulting file size 😄 .

**Comment by lahmatiy** [comment]
Ok, now it's clear to me. Your initial change (win `.npmignore`) were correct then. Revert to it please.
Until new version is published you mat generate this file by `npm run gen:syntax` or create a file by yourself.

**Comment by lahmatiy** [comment]
@philschatz I'm preparing for new release soon. Could you please revert your changes to initial state? I would like to merge it.

**Comment by philschatz** [comment]
ok, I removed the extra commit. Thanks for the feedback!

**Pull request merged**
