### PR TITLE
Add `-moz-initial` keyword

### PR DESCRIPTION
**Pull request by Mouvedia**
for context check stylelint/stylelint#6511
see https://bugzilla.mozilla.org/show_bug.cgi?id=80887#c24

### CODE REVIEW

**Comment by Mouvedia** [comment]
@lahmatiy is there anything I can do to help this PR being merged?

**Comment by lahmatiy** [comment]
@Mouvedia I'm somewhat puzzled. I delved into the history of the keyword and discovered that it became unprefixed in Firefox 19, which was released over a decade ago (February 2013). MDN indicates that it was removed in Firefox 24 ([link](https://developer.mozilla.org/en-US/docs/Web/CSS/initial#browser_compatibility)), although I wasn’t able to corroborate this with the release notes. Given this, I'm struggling to see the necessity to support such an outdated keyword. My research hasn’t revealed where and why this keyword was initially deemed essential. Could it be that I've overlooked something?

**Comment by Mouvedia** [comment]
@lahmatiy we are using csstree as a dependency in a rule of stylelint. Stylelint is used not only on greenfield projects but also on existing codebases that need to be maintained. These codebases may be considered old by your standards but—for example—the sass mixins that were used back then to achieve cross-browser styling shouldn't be considered invalid.

What I am advocating in essence is, if doesn't go against csstree goals outright, it's harmless and useful to other projects, the addition should be warranted.

**Comment by lahmatiy** [comment]
With CSSTree v3.0.1 the issue now can be fixed with `fork({ cssWideKeywords: ['-moz-initial'] })`

**Pull request closed without merging**
