### PR TITLE
Generate walker code at build time

### PR DESCRIPTION
**Pull request by sethfowler**
Let me start by saying that CSSTree is an awesome library. The AST design is great, and the speed is impressive. Thanks so much for writing it, @lahmatiy!

At the moment, though, I'm running into an issue that prevents me from using it. Currently `lib/walker/create.js` generates some iterator code at runtime using `new Function()`. This unfortunately makes it impossible to use this library in the browser on many sites, because eval-like functions are generally blocked by content security policy when CSP is in use.

This PR fixes that by generating that iterator code at build time instead of runtime. A new `gen-walker-code.js` script does the work; it places its output in `dist/walker-generated.js`. I moved some of the other data structures that `lib/walker/create.js` generates into the same file so that all of the related code could be moved out of `lib/walker/create.js`. It seems like a win to generate as much stuff at build time as possible.

@lahmatiy, it has been quite a while since I've written code in the style used in this project, so I probably haven't done things in the best way. I'm happy to make any changes you'd like, so feel free to be as critical as possible. I hope you approve of the general idea at least; I'd love to get this upstreamed and get rid of my fork.

I didn't bump the version in `package.json` because I thought you might want to handle that, but let me know if you'd like me to include that change in the patch.

### CODE REVIEW

**Comment by sethfowler** [comment]
@lahmatiy, I'm not sure what to do about the coverage issue. Do I need to add a test for `gen-walker-code.js` itself? Presumably the new script is what's causing coverage to decrease.

**Comment by lahmatiy** [comment]
@sethfowler Thank you for your effort!
Yep, CSP issue make sense. I was thinking a lot how to avoid runtime compile and keep walker's performance at a good point. Of cause, I had thought to move walker's compilation on build (publish) stage. However, it breaks extensibility, since CSSTree is designed to have an ability to extend syntax and AST format. Take in account extensibility, I see a solution to generate fast walkers on build stage for "default" syntax and use slow walkers for syntax forks (it will be nice to have an option to compile walkers for fork syntaxes as well). In your solution walkers for default syntax is hardcoded, no options for syntax forks at the moment.
Another side of pre-generation of walker functions is growing library size. I don’t know how significant the impact is here, but we need to check it before choosing an approach.
And last one, I had no time to complete design of walkers, so it has several issues to solve, such as:
- References for closest ancestor of some type should be opt-in.
- A simple way to get node's path stack should exist
- Walkers should be abortable
- etc

I write in details to explain why walker's design is still in its current state, and why #91 is still open (@jbraithwaite sorry about it). I don't want a semi-solution and back to walkers design again.

I think #91 is better solution for now. To have a compromise we can have 2 build versions of the library, with runtime compilation and without.

**Comment by lahmatiy** [comment]
I had merged #91, and it's available as [v1.0.0-alpha.35](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.35)

**Comment by sethfowler** [comment]
@lahmatiy That makes sense; I hadn't realized that you were meant to be able to extend the syntax dynamically like that. That's a great feature!

Later this week I'll benchmark this PR against v1.0.0-alpha.35 and see if it's worth the effort to pregenerate the walkers for the default syntax. If there's not a significant performance difference, then I'll just close the PR; otherwise, like you say, we could consider supporting both approaches.

**Comment by lahmatiy** [comment]
@sethfowler You may see example of syntax extension in [stylelint-validator](https://github.com/csstree/stylelint-validator/blob/master/index.js#L2).

Benchmarks would be nice to have. Even if there is no significant difference, we can keep benchmark in csstree repo for future approaches.

Looking forward for benchmark numbers!

**Comment by lahmatiy** [comment]
I made a dirty benchmark. Results:
```
-    current solution (alpha.35) x 407 ops/sec ±1.82% (89 runs sampled)
-    compose functions x 387 ops/sec ±3.69% (88 runs sampled)
-    compile (prior alpha.35) x 557 ops/sec ±1.65% (90 runs sampled)
Fastest test is compile (prior alpha.35) at 1.37x faster than current solution (alpha.35)

compile (prior alpha.35):    2 ms (1.4 times faster)
current solution (alpha.35): 2 ms
compose functions:           3 ms (1.1 times slower)
```

`compose functions` is another approach, that I tried, but no luck it's slower than current. So looks like compilation makes walker 1.4 times faster. Interesting what you'll get.

**Comment by lahmatiy** [comment]
Closing it since no activity.

**Pull request closed without merging**
